server {
  listen 8080;
  root /app;

  location /config {
    alias /app/config/;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;
    try_files $uri$args $uri$args/ =404;
  }

  location /consumer/api/management/ {
    proxy_pass http://app:8000/proxy/consumer/management/;
  }

  location /consumer/api/protocol/ {
    proxy_pass http://app:8000/proxy/consumer/protocol/;
  }

  location /consumer/api/ {
    proxy_pass http://app:8000/proxy/consumer/default/;
  }

  location /provider/api/management/ {
    proxy_pass http://app:8000/proxy/provider/management/;
  }

  location /provider/api/protocol/ {
    proxy_pass http://app:8000/proxy/provider/protocol/;
  }

  location /provider/api/ {
    proxy_pass http://app:8000/proxy/provider/default/;
  }

  location /aas/api/ {
    proxy_pass http://app:8000/proxy/aas/registry/;
  }

  location /api/v1/ {
    proxy_pass http://app:8000/api/v1/;
  }

  location / {
    alias /app/;
    index index.html;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;
    try_files $uri$args $uri$args/ /index.html;
  }
}
