server {
  listen 8080;
  root /app;

  location /config {
    alias /app/config/;
    try_files $uri$args $uri$args/ =404;
  }

  location /consumer/api/management/ {
    proxy_pass http://app:8000/proxy/consumer/management/;
  }

  location /consumer/api/protocol/ {
    proxy_pass http://app:8000/proxy/consumer/protocol/;
  }

  location /consumer/api/ {
    proxy_pass http://app:8000/proxy/consumer/default/;
  }

  location /provider/api/management/ {
    proxy_pass http://app:8000/proxy/provider/management/;
  }

  location /provider/api/protocol/ {
    proxy_pass http://app:8000/proxy/provider/protocol/;
  }

  location /provider/api/ {
    proxy_pass http://app:8000/proxy/provider/default/;
  }

  location / {
    alias /app/;
    index index.html;
    try_files $uri$args $uri$args/ /index.html;
  }
}
